/*
 * Timer1_Private.h
 *
 * Created: 3/20/2024 4:56:04 PM
 *  Author: Roaa Aiman 
 */ 


#ifndef TIMER1_PRIVATE_H_
#define TIMER1_PRIVATE_H_

#define TIMER1_NO_CLK					0
#define TIMER1_CLK_NO_PRESCALER			1
#define TIMER1_CLK_DIVIDED_BY_8			2
#define TIMER1_CLK_DIVIDED_BY_64		3
#define TIMER1_CLK_DIVIDED_BY_256		4
#define TIMER1_CLK_DIVIDED_BY_1024		5
#define TIMER1_CLK_ON_FALLING_EDGE		6
#define TIMER1_CLK_ON_RISING_EDGE		7

#define TIMER1_NON_PWM_NORMAL_OPERATION	    1
#define	TIMER1_NON_PWM_TOGGLE_ON_COMPARE	2
#define TIMER1_NON_PWM_SET_ON_COMPARE		3
#define TIMER1_NON_PWM_CLEAR_ON_COMPARE  	4

#define TIMER1_FAST_PWM_NORMAL_OPERATION	1
#define	TIMER1_FAST_PWM_TOGGLE_ON_COMPARE	2
#define TIMER1_FAST_PWM_SET_ON_COMPARE		3
#define TIMER1_FAST_PWM_CLEAR_ON_COMPARE	4

#define TIMER1_PHASE_CORRECT_NORMAL_OPERATION		1
#define	TIMER1_PHASE_CORRECT_TOGGLE_ON_COMPARE		2
#define TIMER1_PHASE_CORRECT_SET_ON_COMPARE	     	3
#define TIMER1_PHASE_CORRECT_CLEAR_ON_COMPARE		4

/*Waveform Generation Mode Bit*/
#define	TIMER1_NORMAL_MODE								1
#define TIMER1_PWM_PHASE_CORRECT_8_Bit_MODE				2
#define	TIMER1_PWM_PHASE_CORRECT_9_Bit_MODE				3
#define TIMER1_PWM_PHASE_CORRECT_10_Bit_MODE			4
#define TIMER1_CTC_MODE_OCR1A							5
#define	TIMER1_FAST_PWM_8_Bit_MODE						6
#define	TIMER1_FAST_PWM_9_Bit_MODE						7
#define	TIMER1_FAST_PWM_10_Bit_MODE						8
#define	TIMER1_PWM_PHASE_FREQUENCY_CORRECT_MODE_ICR1	9
#define TIMER1_PWM_PHASE_FREQUENCY_CORRECT_MODE_OCR1A	10
#define	TIMER1_PWM_PHASE_CORRECT_MODE_ICR1				11
#define	TIMER1_PWM_PHASE_CORRECT_MODE_OCR1A				13
#define TIMER1_CTC_MODE_ICR1							14
#define TIMER1_FAST_PWM_MODE_ICR1						15
#define TIMER1_FAST_PWM_MODE_OCR1A						16

#define TIMER1_CHANNEL_A	1
#define TIMER1_CHANNEL_B	2





#endif /* TIMER1_PRIVATE_H_ */