/*
 * ADC_config.h
 *
 * Created: 3/4/2024 12:58:45 PM
 *  Author: SMART
 */ 


#ifndef ADC_CONFIG_H_
#define ADC_CONFIG_H_



#define ADC_CHANNEL_1 0
#define ADC_CHANNEL_2 1
#define ADC_CHANNEL_3 2
#define ADC_CHANNEL_4 3
#define ADC_CHANNEL_5 4
#define ADC_CHANNEL_6 5
#define ADC_CHANNEL_7 6
#define ADC_CHANNEL_8 7

/* CHOOSE AVCC OR AVREF OR INTERNAL */
#define VOLTAGE_REFERENCE_AVREF     0
#define VOLTAGE_REFERENCE_AVCC      1
#define VOLTAGE_REFERENCE_INTERNAL  2


#define RIGHT_ADJUSTMENT  0

#define LEFT_ADJUSTMENT   1


/*****/
#define SINGLE_CONVERSION 	0
#define AUTOTRIGGERED 		1
/*****/

#define FREE_RUNNING_MODE   0
/*****/

#define  DIVID_BY_2    2
#define  DIVID_BY_4    4
#define  DIVID_BY_8    8
#define  DIVID_BY_16  16
#define  DIVID_BY_32  32
#define  DIVID_BY_64  64
#define  DIVID_BY_128  128

#define INTERRUPT_ENABLE 1
#define INTERRUPT_DISABLE 0

#define ADC_ENABLE  1
#define ADC_DISABLE  0

/* CHOOSE RIGHT_ADJUSTMENT OR LEFT_ADJUSTMENT */
#define ADJUSTMENT					RIGHT_ADJUSTMENT


/* CHOOSE SINGLE_CONVERSION MODE OR AUTOTRIGGERED MODE*/
#define ADC_AUTOTRIGGERED_MODE					SINGLE_CONVERSION

/* CHOOSE FROM (FREE_RUNNING_MODE,ANALOG_COMPARATOR,EXTI0,
 * TIMER0_COMPARE_MATCH,TIMER0_OVERFOLW,TIMER0_COMPARE_MATCH
 * TIMER1_COMPARE_MATCH, TIMER1_OVERFLOW,TIMER1_CAPTUREEVENT
 * */
#define ADC_AUTO_TRIGGER_SOURCE		FREE_RUNNING_MODE

/* CHOOSE DIVIDE_BY_2,4,8,16,32,64,128 */
#define ADC_PRESCALLER				DIVID_BY_128

#define ADC_MODE         ADC_ENABLE

#define INTTERUPT_MODE   INTERRUPT_DISABLE
						
#endif /* ADC_CONFIG_H_ */
						   